# Server Configuration
server.port=8080

# MongoDB Atlas Configuration
spring.data.mongodb.uri=mongodb://PAF:Sonal123@ac-9hrtwwo-shard-00-00.1i0mouu.mongodb.net:27017,ac-9hrtwwo-shard-00-01.1i0mouu.mongodb.net:27017,ac-9hrtwwo-shard-00-02.1i0mouu.mongodb.net:27017/campus_hub?ssl=true&replicaSet=atlas-o4j6ys-shard-0&authSource=admin&retryWrites=true&w=majority&tlsAllowInvalidCertificates=true

# Jackson Configuration for LocalDateTime
spring.jackson.serialization.write-dates-as-timestamps=false

# Logging
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
