# Server Configuration
server.port=8080

# MongoDB Atlas Configuration
spring.data.mongodb.uri=mongodb+srv://PAF:Sonal123@cluster0.1i0mouu.mongodb.net/campus_hub?retryWrites=true&w=majority&appName=Cluster0

# Jackson Configuration for LocalDateTime
spring.jackson.serialization.write-dates-as-timestamps=false

# Logging
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
